const GET_MESSAGES = 'GET_MESSAGES';
const ADD_MESSAGES = 'ADD_MESSAGES';
const INSERT_MESSAGE_DATA = 'INSERT_MESSAGE_DATA'

const GET_ERROR_MESSAGE_DATA = 'GET_ERROR_MESSAGE_DATA';

export {
    GET_MESSAGES,
    ADD_MESSAGES,
    INSERT_MESSAGE_DATA,
    GET_ERROR_MESSAGE_DATA,
};
